---
- hosts: servers
  remote_user: root
  gather_facts: False
  tasks:
    - name: Set project and network range
      set_fact:
        test_range: "{{ range(0, projects, 1) | list }}"
      tags:
        - project
        - quota
        - network
    
    - name: Create projects
      shell: |
        source {{ openrc }} && openstack project create --or-show {{ project_prefix }}{{ item }} \
        && openstack role add --project {{ project_prefix }}{{ item }} --user admin admin
      with_items: "{{ test_range }}"
      tags:
        - project
      
    - name: Reset resource quotas
      shell: |
        source {{ openrc }}
        for n in loadbalancer healthmonitor l7policy listener member pool; do
          echo -n "$n .. " 
          neutron --os-project-name {{ project_prefix }}{{ item }} quota-update --$n -1 > /dev/null 2>&1
        done
      with_items: "{{ test_range }}"
      tags:
        - quota

    - name: Create networks
      shell: |
        source {{ openrc }}
        project_id=`openstack project show {{ project_prefix }}{{ item }} --format value --column id`
        exists=`neutron net-list --format value --column name | grep "^{{ network_prefix }}{{ item }}$"`
        set -e
        if [ $? -eq 0 -a "$exists" != "net-{{ item }}" ]; then
          neutron net-create --tenant-id $project_id --provider:network_type vlan --provider:physical_network {{ physical_network }} {{ network_prefix }}{{ item }} --provider:segmentation_id {{ 200 + item | int }}
          neutron subnet-create --tenant-id $project_id --name {{ subnet_prefix }}{{ item }} {{ network_prefix }}{{ item }} 100.{{ item }}.0.0/16
        fi
      with_items: "{{ test_range }}"
      tags:
        network
